In [2]:
#Why numpy
import numpy
import time

size = 1000000

list1 = range(size)
list2 = range(size)

array1 = numpy.arange(size)
array2 = numpy.arange(size)

initialTime = time.time()

resultantList = [(a * b) for a,b in zip(list1, list2)]

print("Time taken by the Lists to perform multiplication:",
      (time.time() - initialTime),
      "seconds")
initialTime = time.time()

resultantArray = array1 * array2

print("Time taken by Numpy Arrays to perform multiplication:",
      (time.time() - initialTime),
      "seconds")

Time taken by the Lists to perform multiplication: 0.39353036880493164 seconds
Time taken by Numpy Arrays to perform multiplication: 0.008149147033691406 seconds


In [4]:
#numpy array with numbers
import numpy as np
list1 = [1,2,3,4,5,6]
a = np.array(list1)

print('list1',list1)
print('numpy array',a)

list1 [1, 2, 3, 4, 5, 6]
numpy array [1 2 3 4 5 6]


In [5]:
#converting array to list
a = np.array(list1, dtype = float)
print(a)

list2 = list(a)
list3 = a.tolist()
print(list3)

[1. 2. 3. 4. 5. 6.]
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0]


In [6]:
#2D Numpy array creation
a = np.array([[1, 2, 3, 45],
              [4, 5, 6, 56],
              [41, 15, 1, 1]
             ])
a

array([[ 1,  2,  3, 45],
       [ 4,  5,  6, 56],
       [41, 15,  1,  1]])

In [9]:
#3D NumPy array creation
a = np.array([[[1,2],
               [3,4]],
               [[5, 6],
                [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
a_list = [[[1,2,3],[3,4,5]],[[2,4,5],[6,7,8]]]
len(a_list)

2

In [11]:
a_list = [[[1,2,3],[3,4,5]],[[2,4,5],[6,7,8]]]

print(len(a_list))
print(len(a_list[0]))
print(len(a_list[0][0]))

2
2
3


In [12]:
a_list = [[[1,2,3],[3,4,5]],[[2,4,5],[6,7,8]]]

a_array = np.array(a_list)
print(a_array.shape)

(2, 2, 3)


In [14]:
#Generate numpy array od dimension 1024*728 = using reshape() function
import numpy as np

#a_array = np.array([i for i in range(1024)] for j in range(728)) 

a_array = np.arange(1024*728)
a_array1 = a_array.reshape(1024,728)
print(a_array.shape)
print(a_array1.shape)
a_array1.reshape(745472).shape


(745472,)
(1024, 728)


(745472,)

In [6]:
a = np.arange(8)
a.reshape(2,2,2)
print(a)
b = np.arange(1,14,2)
print(b)

[0 1 2 3 4 5 6 7]
[ 1  3  5  7  9 11 13]


In [7]:
b = np.array([1,2,3,4,5,6,7,8,9])
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [16]:
#Numpy Zero array
zeros = np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
ones = np.ones((4,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [18]:
zeros[0:2]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
a_array = np.array([[2,34,5,6],[34,566,879,5],[3,5,6,8]])
print(a_array.shape)
a_array[2,2]
a_array[0:2,0:2]

(3, 4)


array([[  2,  34],
       [ 34, 566]])

In [23]:
#Slicing of array based questions
import numpy as np

arr1d = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr1d[2:6])
print(arr1d[:3])
print(arr1d[5:])
print(arr1d[::2])
print(arr1d[-3:])

[3 4 5 6]
[1 2 3]
[ 6  7  8  9 10]
[1 3 5 7 9]
[ 8  9 10]


In [25]:
import numpy as np
arr2d = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])
print(arr2d[1,1])
print(arr2d[:2,1:])
print(arr2d[:,1])


5
[[2 3]
 [5 6]]
[2 5 8]


In [4]:
#Numpy Array of random Numbers
import numpy as np
data = np.random.random(20)
print(data)

[0.14788162 0.97169475 0.97674913 0.24468444 0.50255444 0.07917373
 0.9844702  0.81257134 0.61656092 0.9134919  0.21106956 0.8907774
 0.06471225 0.99723671 0.59891674 0.53288378 0.64581899 0.18480165
 0.20843711 0.2682738 ]


In [29]:
#use of rand function
data1 = np.random.rand(20)
data2 = np.random.rand(2,3)
data3 = np.random.rand(2,3,4)

print(data1)
print(data2)
print(data3)
print(data2.shape)
print(data2.size)

[0.03614155 0.4164488  0.28601416 0.11475864 0.49599232 0.16033951
 0.68390597 0.88449955 0.9513864  0.61501481 0.95539426 0.31022529
 0.4334928  0.0992198  0.91429235 0.94537748 0.9018407  0.9124656
 0.34273575 0.87906436]
[[0.11455389 0.26538895 0.36087542]
 [0.50908778 0.23610189 0.29449116]]
[[[0.58116987 0.67623325 0.07041068 0.30484696]
  [0.89109634 0.78058338 0.35731801 0.74603506]
  [0.43092378 0.84464495 0.49766974 0.39557357]]

 [[0.03660205 0.59027113 0.12340289 0.67732493]
  [0.46181461 0.48541948 0.91263422 0.45105563]
  [0.80925747 0.74330182 0.83531625 0.89282233]]]
(2, 3)
6


In [30]:
data = np.random.randn(2,3)
print(data)

[[-2.19859471 -0.92240695  0.29199438]
 [-2.35145419 -1.83937813 -0.47787434]]


In [31]:
#use of randint
data = np.random.randint(-10,20,5)
print(data)

[ 9 -9 16 -8 16]


In [32]:
data = np.random.randint(1,20,(4,2,3))
print(data)

[[[10  1 18]
  [18 13  8]]

 [[17 17 13]
  [12  6 15]]

 [[17 13 15]
  [ 1  1  2]]

 [[ 3  3  9]
  [ 2  4 15]]]


In [33]:
data = np.linspace(1,10,5)
print(data)

[ 1.    3.25  5.5   7.75 10.  ]


In [34]:
data = np.arange(1,10,5)
print(data)

[1 6]


In [38]:
#Exercise1
zeros = np.zeros((4,5))
print(zeros)
ones = np.ones((3,6))
print(ones)
data = np.random.randn(2,10)
print(data)
data2 = np.random.randint(230,500,(6,3))
print(data2)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[ 0.86375177 -0.06588448  0.26532281  1.9591101   0.28253601  0.10297784
   1.76421821 -0.439687    1.10527047  2.47349885]
 [ 0.39568808 -0.0250097   0.79876735  0.24175384 -1.36477975  0.74891239
  -0.6680552  -0.83438341  1.02143095  0.06393077]]
[[377 241 491]
 [499 453 333]
 [302 412 271]
 [250 312 444]
 [419 432 230]
 [385 262 483]]


In [40]:
#Generate a random float values of a guassian pdf for the dimension(4,5)
data = np.random.randn(4,5)
print(data)

[[ 1.10574407 -0.1950674  -0.90923821  0.39044191 -0.14402268]
 [ 0.6436056   1.75289601 -0.40206469 -1.33921992  0.13305882]
 [-0.55303573  3.65238534  0.82955949 -0.1989755  -1.36879449]
 [ 0.14461014 -1.39912248 -1.43255071 -0.52648258  0.94314703]]


In [42]:
data = np.random.randint(2,23,(4,5))
print(data)

[[15 16 21 17  4]
 [20 15 22 17 12]
 [15 12  6  9 10]
 [22 18 11 16  2]]


In [46]:
#Generate random floating value using randn() for the range between 20 to 200 of 1D array(size = 20)
scaled_number = 20+(200-20)*np.random.rand(20)
print(scaled_number)
original = np.random.randn(20)
print(original)
scaled_number = 20+(200-20)*((original - original.min())/(original.max()-original.min()))
print(scaled_number)

[ 77.08940811  55.66909523 134.8535558  125.40979674 132.43927203
 134.59716581 164.016807   113.74550913 143.47462382 159.24527965
  69.40834502  29.4288227  156.44163387  38.26190744  39.82946536
 114.43584182  98.04889728 196.37973995  61.92890934  61.82270027]
[-0.44373636  0.352348    1.79094774 -0.18322977  1.21954355 -0.10496133
  0.82225035 -0.67225269 -0.5537186  -0.73368286 -0.37827315  1.7562241
 -0.85923679 -2.47658994  1.76959814 -0.35365175  0.58427815  0.1899882
 -1.14295266 -1.38254807]
[105.74350649 139.32146073 200.         116.73138493 175.89880588
 120.03266116 159.14141981  96.10494125 101.10457761  93.51388503
 108.50467192 198.53539565  88.21815971  20.         199.09949769
 109.54317543 149.10401669 132.4733046   76.25133949  66.14547089]


In [2]:
#creating matrix filled with same value
import numpy as np
np.full((3,3), fill_value=15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [5]:
#create identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
data1 = np.linspace(1,100,26)
print(data1)
data2 = np.arange(50,150,3)
print(data2)
np.full((5,5),fill_value=27)
np.eye(3,4)

[  1.     4.96   8.92  12.88  16.84  20.8   24.76  28.72  32.68  36.64
  40.6   44.56  48.52  52.48  56.44  60.4   64.36  68.32  72.28  76.24
  80.2   84.16  88.12  92.08  96.04 100.  ]
[ 50  53  56  59  62  65  68  71  74  77  80  83  86  89  92  95  98 101
 104 107 110 113 116 119 122 125 128 131 134 137 140 143 146 149]


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [14]:
mata = np.array([[1,2,3],
                 [3,4,3],
                 [8,9,6]])
det_a = np.linalg.det(mata)
print(det_a)
inv_a = np.linalg.inv(mata)
print(inv_a)
eig_a = np.linalg.eig(mata)
print(eig_a)

-5.999999999999998
[[ 0.5        -2.5         1.        ]
 [-1.          3.         -1.        ]
 [ 0.83333333 -1.16666667  0.33333333]]
EigResult(eigenvalues=array([12.76498204, -2.        ,  0.23501796]), eigenvectors=array([[-2.89582287e-01, -7.07106781e-01,  5.82151548e-01],
       [-3.97183873e-01, -3.05058243e-16, -7.37185496e-01],
       [-8.70854219e-01,  7.07106781e-01,  3.43011837e-01]]))


In [16]:
matrix = np.array([[1,2],
                   [3,4]])
det = np.linalg.det(matrix)
inverse = None
if det!=0:
    inverse = np.linalg.inv(matrix)
print(det)
print(inverse)

-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [18]:
a = np.array([1,2,3,4])
bool_a = a>2
print(bool_a)


[False False  True  True]


In [19]:
arr = np.array([10,20,30,40,50,60])
print(arr[arr>30])
print(arr[arr%2==0])

[40 50 60]
[10 20 30 40 50 60]


In [22]:
""" calculate the covariance of a 3*3 matrix"""
matrix = np.array([[10, 2, 35], [41, 5, 62], [71, 8, 9]])
print(np.cov(matrix))

[[ 296.33333333  449.         -168.83333333]
 [ 449.          831.          170.5       ]
 [-168.83333333  170.5        1302.33333333]]


In [24]:
A = np.array([[2,1],[1,3]])
b = np.array([7,10])
x = np.linalg.solve(A,b)
print(x)
print(np.dot(A,x))


[2.2 2.6]
[ 7. 10.]
